---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - python:
          mass_threshold: 50
  fixme:
    enabled: true
  radon:
    enabled: true
  markdownlint:
    enabled: true
  pep8:
    enabled: true
ratings:
  paths:
  - "**.py"

exclude_paths:
- tests/
- .venv/
- .cache/
- build/
