 duplication:
    enabled: true
    config:
      languages:
      - python

  fixme:
    enabled: true
  markdownlint:
    enabled: true
  pep8:
    enabled: true

ratings:
  paths:
  - "**.inc"
  - "**.module"
  - "**.py"
exclude_paths:
- tests/
- docs/