language: python
python:
  - "2.7"

install:
  - pip install .
  - pip install -r requirements.txt
  - pip install coverage

script:
  - pytest
  - coverage run -m csmon.cli --urls 'http://www.google.com!!!<title>Google</title>'

after_success:
  - CODECLIMATE_REPO_TOKEN=5c7dbe2c9715eab293d17b3a3dd65709f24b0e9330aee8505ef0d6e96dfa8756 codeclimate-test-reporter