language: python
python:
  - "2.6"
  - "2.7"

install:
  - pip install .
  - pip install -r requirements.txt
  - pip install coverage

script:
  - pytest
  - coverage run -m csmon.cli

after_success:
  - CODECLIMATE_REPO_TOKEN=a8ca0741806cc58417861626c816bfa223508d9b codeclimate-test-reporter